# include <scale.h>

int		tab;

void	write_s(FILE *fd, char *name, char *string, int is_md) {
	if (!strlen(string)) {
		string = malloc(3);
		strcpy(string, "''");
		is_md = 0;
	}
	if (tab) {
		for (int i = 0; i < tab; fprintf(fd, " "), i++);
	}
	if (is_md) {
		fprintf(fd, "%s: |\n", name);
		for (int i = 0; string[i]; i++) {
			if (!i && string[i] != '\n')
				fprintf(fd, "\n");
			if ((i > 1 && string[i - 1] == '\n') || !i) {
				if (string[i] == '\n' && !i)
					fprintf(fd, "\n");
				for (int j = 0; j < tab + 2; fprintf(fd, " "), j++);
				if (string[i] == '\n' && !i)
					i++;
			} 
			fprintf(fd, "%c", string[i]);
		}
		if (string[strlen(string) - 1] != '\n')
			fprintf(fd, "\n");
		fprintf(fd, "\n");
	}
	else
		fprintf(fd, "%s: %s\n", name, string);
}

void	write_i(FILE *fd, char *name, int val) {
	if (tab) {
		for (int i = 0; i < tab; fprintf(fd, " "), i++);
	}
	fprintf(fd, "%s: %d\n", name, val);
}

void	print_sections(scale *s, FILE *fd) {
	int		position = 1, pos2;
	scale_sections		*it;
	scale_questions		*qt;
	scale_skills		*sk;

	for (it = s->sections; it; it = it->next) {
		fprintf(fd, "# BEGINNING OF SECTION %s #\n", it->name.buf);
		tab = 0;
		write_s(fd, "- name", it->name.buf, 0);
		tab = 2;
		write_i(fd, "position", position++);
		write_s(fd, "description", it->description.buf, 1);
		for (int i = 0; i < tab; fprintf(fd, " "), i++);
		fprintf(fd, "questions:\n");
		pos2 = 1;
		for (qt = it->questions; qt; qt = qt->next) {
			fprintf(fd, "  # Question %s #\n", qt->name.buf);
			tab = 2;
			write_s(fd, "- name", qt->name.buf, 0);
			tab = 4;
			write_i(fd, "position", pos2++);
			qt->guidelines.buf[qt->guidelines.len] = 0;
			write_s(fd, "guidelines", qt->guidelines.buf, 1);
			if (qt->rating.val == R_BOOL) {
				write_s(fd, "rating", "bool", 0);
			} else if (qt->rating.val == R_MULTI) {
				write_s(fd, "rating", "multi", 0);
			}
			if (qt->kind.val == R_STAND) {
				write_s(fd, "kind", "standard", 0);
			} else if (qt->kind.val == R_BONUS) {
				write_s(fd, "kind", "bonus", 0);
			}
			for (int i = 0; i < tab; fprintf(fd, " "), i++);
			fprintf(fd, "questions_skills:\n");
			for (sk = qt->skills; sk; sk = sk->next) {
				write_i(fd, "- percentage", sk->percent.val);
				tab = 6;
				write_s(fd, "name", sk->name.buf, 0);
				tab = 4;
			}
		}
		fprintf(fd, "\n# END OF SECTION #\n\n");
	}
}

void	save_scale(scale *s) {
	FILE	*fd = fopen(s->o_file, "w+");

	tab = 0;
	if (!fd) {
		ERROR("Cannot open %s for writing\n", s->o_file);
	}
	fprintf(fd, "#############################################\n# This scale has been generated by 42_scale #\n#############################################\n");
	write_s(fd, "name", s->name.buf, 0);
	if (s->lang.val == LANG_EN) {
		write_s(fd, "lg", "en", 0);
	} else if (s->lang.val == LANG_FR) {
		write_s(fd, "lg", "fr", 0);
	} else if (s->lang.val == LANG_RU) {
		write_s(fd, "lg", "ru", 0);
	}
	fprintf(fd, "is_primary: true\n\n");
	write_s(fd, "comment", s->comment.buf, 0);
	write_s(fd, "introduction_md", s->intro.buf, 1);
	write_s(fd, "disclaimer_md", s->disclaimer.buf, 1);
	write_s(fd, "guidelines_md", s->guidelines.buf, 1);
	write_i(fd, "correction_number", s->correction_n.val);
	write_i(fd, "duration", s->duration.val);
	fprintf(fd, "\n# **************************************************************************** #\n\n");
	fprintf(fd, "sections:\n");
	print_sections(s, fd);
	fclose(fd);
}
